# Generated by Django 5.1.2 on 2024-10-27 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('commerce_id', models.AutoField(primary_key=True, serialize=False)),
                ('commerce_name', models.CharField(max_length=50)),
                ('commerce_description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
                ('commerce_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerces', to='client_app.commercecategory')),
            ],
        ),
    ]
