# Generated by Django 5.1.2 on 2024-10-27 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_commerceproduct'),
        ('production_app', '0003_order_product_orderdetail_menuproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerceproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_products', to='production_app.product'),
        ),
    ]
