# Generated by Django 5.1.2 on 2024-10-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('web_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')])),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('section_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_web', models.CharField(max_length=100)),
                ('section_description', models.TextField()),
            ],
        ),
    ]
