# Generated by Django 5.1.2 on 2024-10-27 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_commerce'),
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingCommerce',
            fields=[
                ('landing_commerce_id', models.AutoField(primary_key=True, serialize=False)),
                ('commerce_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_commerces', to='client_app.commerce')),
                ('landing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_commerces', to='web_app.landing')),
            ],
        ),
        migrations.CreateModel(
            name='LandingDetail',
            fields=[
                ('landing_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('landing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='web_app.landing')),
                ('section_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_details', to='web_app.sectiontype')),
            ],
        ),
    ]
